### ISSUE TITLE
Build libspatialindex_c as a static library

### ISSUE THREAD

**Issue by urschrei** [libspatialindex/libspatialindex#102]
I'd like to build libspatialindex (specifically, `libspatialindex_c`) as a static library,  but I'm not sure whether the `CMake` configuration supports it. I can see a setting for `CMAKE_ARCHIVE_OUTPUT_DIRECTORY`, but running

    cmake -DCMAKE_INSTALL_PREFIX=/outputdir -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off .
Only copies the dylibs into `/outputdir/lib`.

Is there a way to accomplish this using the `CMake` setup?

**Comment by hobu** [comment]
The CMake configuration for libspatialindex doesn't currently support static builds. You will need to tweak the *CMakeLists.txt* file to change the output type from SHARED to STATIC. You possibly might also need to make a few more tweaks, I'm not sure.

**Comment by urschrei** [comment]
Ah, I'll stick to the Autotools version, in that case. Thanks!
