### ISSUE TITLE
Does your Rtree scale to vector of 512 dimensions?

### ISSUE THREAD

**Issue by yxchng** [libspatialindex/libspatialindex#104]
Does your Rtree scale to vector of 512 dimensions?

**Comment by kounoupis** [comment]
R-trees are meaningless beyond ... 5 to 10 dimensions. They devolve to
performance worse than a linear scan. Look for high-dimensional indexing
structures if you want to index points with 512 dimensions.

**Comment by hobu** [comment]
> R-trees are meaningless beyond ... 5 to 10 dimensions.

Oh, you should have just said, "Yes, libspatialindex goes to 11!"
