### ISSUE TITLE
MSVC version check breaking build

### ISSUE THREAD

**Issue by sigstop** [libspatialindex/libspatialindex#115]
When building in a Docker container, I ran into this error.  The work around was to comment out the test in gtest/CMakeLists.txt

Step 6/12 : RUN git clone https://github.com/libspatialindex/libspatialindex.git
 ---> Running in f753b25c6dbb
Cloning into 'libspatialindex'...
Removing intermediate container f753b25c6dbb
 ---> 5bfec7455474
Step 7/12 : RUN cd libspatialindex && cmake . 	-DCMAKE_INSTALL_PREFIX=/usr         -DCMAKE_SYSTEM_NAME=Linux         -DCMAKE_BUILD_TYPE=Release &&  make  &&  make install
 ---> Running in 5bcc1da573ed
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for srand48
-- Looking for srand48 - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Looking for bcopy
-- Looking for bcopy - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Setting libspatialindex build type - Release
CMake Error at test/gtest/CMakeLists.txt:1 (if):
  if given arguments:

    "MSVC_VERSION" "GREATER_EQUAL" "1900"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/usr/local/src/libspatialindex/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cd libspatialindex && cmake . 	-DCMAKE_INSTALL_PREFIX=/usr         -DCMAKE_SYSTEM_NAME=Linux         -DCMAKE_BUILD_TYPE=Release &&  make  &&  make install' returned a non-zero code: 1

**Comment by hobu** [comment]
Closing for now. If this is still an issue, please open with a patch demonstrating it.
