### ISSUE TITLE
Byte is now a native type since C++17

### ISSUE THREAD

**Issue by batconjurer** [libspatialindex/libspatialindex#138]
In https://github.com/libspatialindex/libspatialindex/blob/master/include/spatialindex/tools/Tools.h#L78,
a typedef is used to make a type named byte. This conflicts with the native byte type introduced in C++17.

**Comment by mortezaipo** [comment]
I've replaced all `byte` to `uint8_t` and now it works on c++17:
```
$  find . -type f -exec sed -i 's/byte /uint8_t /g' {} \;
$ find . -type f -exec sed -i 's/byte\*/uint8_t\*/g' {} \;
$ find . -type f -exec sed -i 's/byte\[/uint8_t\[/g' {} \;
$ find . -type f -exec sed -i 's/byte)/uint8_t)/g' {} \;
```

**Comment by mortezaipo** [comment]
Pull request already merge: https://github.com/libspatialindex/libspatialindex/pull/140
