### ISSUE TITLE
Does the STR Partitioner works well in high dimension?

### ISSUE THREAD

**Issue by lyp-bobi** [libspatialindex/libspatialindex#148]
I read the code here in rtree::BulkLoader::createLevel() that is 
`uint64_t S = static_cast<uint64_t>(std::ceil(std::sqrt(static_cast<double>(P))));`

While when I read the original paper I find that S should be ceil(pow(P,1/k)) where k is the dimension. 
Is there any special purpose for assuming k=2 here?

**Comment by hobu** [comment]
@kounoupis will have to comment on this.
