### ISSUE TITLE
When compiling in windows, Make creation of DLL optional

### ISSUE THREAD

**Issue by las3rlars** [libspatialindex/libspatialindex#156]
We need some setting in CMake that will make SIDX_DLL set to nothing.

**Comment by hobu** [comment]
What is the case for that? Static builds? If you want a static build without exports, define `WITH_STATIC_LASZIP`. Otherwise, provide a patch that adjusts the code here
https://github.com/libspatialindex/libspatialindex/blob/master/src/CMakeLists.txt#L191

**Comment by hobu** [comment]
Obviously this isn't being used or people would notice it says LASZIP instead of SIDX 😄

**Comment by hobu** [comment]
Changed to `WITH_STATIC_SIDX` for the upcoming release.
