### ISSUE TITLE
Task: update website

### ISSUE THREAD

**Issue by mwtoews** [libspatialindex/libspatialindex#157]
This is an easy task for anyone with GitHub admin access.

The current website is `http://libspatialindex.github.com/` which redirects to `https://libspatialindex.org`

This task is to update the website to `https://libspatialindex.org` using the GitHub website interface.

**Comment by hobu** [comment]
> This task is to update the website to https://libspatialindex.org using the GitHub website interface.

I'm not sure what you mean. Is the redirect wrong?

**Comment by mwtoews** [comment]
there's nothing wrong with the redirect. The homepage can simply be updated to the new name.

**Comment by hobu** [comment]
Ah. If you make a PR that does so, it should be automatically pushed.

**Comment by mwtoews** [comment]
I don't think it's possible to change this with a PR. Usually just edit the value on the GitHub website, at the top, beside the description.

**Comment by hobu** [comment]
change attempt made. Please confirm.

I had no idea what you were pointing at 😄

**Comment by mwtoews** [comment]
nearly there, just change it to https and it's all done!

**Comment by hobu** [comment]
done
