### ISSUE TITLE
Warning about Empty Version in GTest CMakeList File

### ISSUE THREAD

**Issue by mortezaipo** [libspatialindex/libspatialindex#167]
https://github.com/libspatialindex/libspatialindex/blob/0e5c4634b258becb123a7ec03b2e9ddc2fd26eff/test/gtest/gtest-1.10.0/CMakeLists.txt#L54

> CMake Warning at include/libspatialindex/test/gtest/gtest-1.10.0/CMakeLists.txt:54 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

@hobu Should we set the `GOOGLETEST_VERSION` variable before it?

**Comment by hobu** [comment]
Yes, I think so.

We also need to put back the Makefile.am that gtest removed in gtest-1.10.0. We need to support automake too, unless you think we can drop it altogether.

**Comment by hobu** [comment]
btw, please add yourself to https://github.com/libspatialindex/libspatialindex/blob/master/AUTHORS

**Comment by hobu** [comment]
> We also need to put back the Makefile.am that gtest removed in gtest-1.10.0. We need to support automake too, unless you think we can drop it altogether.

googletest has removed all m4/automake support. It is as good as time as any to remove libspatialindex's

**Comment by hobu** [comment]
Please track this in #168

**Comment by mortezaipo** [comment]
> btw, please add yourself to https://github.com/libspatialindex/libspatialindex/blob/master/AUTHORS

Wow! Thank you so much! :pray:
