### ISSUE TITLE
Tarball naming convention changes

### ISSUE THREAD

**Issue by volter** [libspatialindex/libspatialindex#172]
The original pattern was name-src-version. For 1.9.1 it is name-version-src, which also breaks the references on https://libspatialindex.org/

Is this on purpose?

**Comment by hobu** [comment]
No. It was a mistake from switching from autoconf to CMake distribution packaging. 

I'm going to have to release a 1.9.2 pretty soon. There's a significant bug in the nearest neighbor paging stuff that was recently added to the C API.

**Comment by volter** [comment]
Thank you!

**Comment by volter** [comment]
As far as I am concerned, this issue is resolved.

**Comment by hobu** [comment]
1.9.3 released to fix a sorting issue. Hopefully the release train is done for a while now. https://github.com/libspatialindex/libspatialindex/releases/tag/1.9.3
