### ISSUE TITLE
libspatialindex.so.5 or 6 file not found

### ISSUE THREAD

**Issue by mortezaipo** [libspatialindex/libspatialindex#174]
When I compile a project by adding `libspatialindex.so` path, it compiles without any error but when I run my project, it shows this error:

```
$ g++ mycode.cc -o mycode -pthread lib/libspatialindex/bin/libspatialindex.so
$ ./mycode
error while loading shared libraries: libspatialindex.so.5: cannot open shared object file: No such file or directory
```

I've checked the libspatialindex `bin` directory and it contains:
```
libspatialindex_c.so  libspatialindex_c.so.6  libspatialindex_c.so.6.1.1  libspatialindex.so  libspatialindex.so.6  libspatialindex.so.6.1.1
```

**Note:** it worked in the past on the _master_ branch and I don't know what exactly changed recently which leads to have a failure in my compilation process.

Should I have to consider an extra argument in the compilation step? Would you please help me.
Thanks

**Comment by hobu** [comment]
This may have something to do with changing SHARED vs STATIC in the CMake configuration. What happens if you use `-DBUILD_SHARED_LIBS =ON` in your cmake invocation? Do you get different symlinks?

**Comment by mortezaipo** [comment]
> This may have something to do with changing SHARED vs STATIC in the CMake configuration. What happens if you use `-DBUILD_SHARED_LIBS =ON` in your cmake invocation? Do you get different symlinks?

I've tried it but still shows the same message:
```
$ cd lib/libspatialindex/ && cmake . -DBUILD_SHARED_LIBS=ON && make -j8
.... build libspatialindex ....
$ cd - && make -j8
g++ mycode.cc -o mycode -std=c++17 -Ilib/libspatialindex/include/ -pthread lib/libspatialindex/bin/libspatialindex.so 
$ ./mycode
error while loading shared libraries: libspatialindex.so.6: cannot open shared object file: No such file or directory
```

Even I've tried by `-L` and `-I` flags, but errors changed to `undefined reference`:

```
$ cmake . -DBUILD_SHARED_LIBS=ON && make -j8
g++ mycode.cc -o mycode -std=c++17 -Ilib/libspatialindex/include/ -pthread -Llib/libspatialindex/bin/ -Ispatialindex 
................. undefined reference to ~RTree ....
```

**Comment by mortezaipo** [comment]
Actually I've fixed it by setting `LD_LIBRARY_PATH` variable:
```
LD_LIBRARY_PATH=lib/libspatialindex/bin/ ./mycode
```
But is there any other way exists that I can fix it in my Makefile?
My Makefile content is something like this:
```
g++ mycode.cc -o mycode -std=c++17 -Ilib/libspatialindex/include/ -pthread lib/libspatialindex/bin/libspatialindex.so 
```

**Comment by mortezaipo** [comment]
Extra info, when I use in CMake file it works fine:

```
add_subdirectory(include/libspatialindex)
target_link_libraries(mycode spatialindex)
```

The problem should be in my Makefile.
