### ISSUE TITLE
CMake: don't force the build of a shared library (the return)

### ISSUE THREAD

**Issue by SpaceIm** [libspatialindex/libspatialindex#177]
This PR https://github.com/libspatialindex/libspatialindex/pull/158 was supposed to allow static builds with CMake.

But `SET(BUILD_SHARED_LIBS ON)` still forces building shared libs, without possibility for consumers to build static libs. Instead, CMakeLists.txt should use something like `option(BUILD_SHARED_LIBS "Build shared libs" ON)`.

**Comment by mortezaipo** [comment]
Will you send the PR?

**Comment by SpaceIm** [comment]
Sure I will.

I can also dig a little bit more into preprocessing macros related to SIDX_DLL_EXPORT, SIDX_C_DLL and SIDX_DLL, because it doesn't seem to be very clean for proper static or shared build. But it can be another PR.
