### ISSUE TITLE
C API: do not install C++ private headers

### ISSUE THREAD

**Issue by SpaceIm** [libspatialindex/libspatialindex#180]
Currently, CMakeLists installs all header files, but most of headers in capi folder are C++ private headers.
In 1.9.3, only sidx_api.h, sidx_config.h and sidx_export.h should be installed for C API.

**Comment by hobu** [comment]
Are the private headers causing problems? They are indeed private, but I'm indifferent as to whether people have used them or not. Things have changed a little bit, but out release cadence is so slow that I don't think it's been an issue.
