### ISSUE TITLE
Disk based index unreadable when using tcmalloc

### ISSUE THREAD

**Issue by spansh** [libspatialindex/libspatialindex#187]
When using the google malloc etc tools from http://goog-perftools.sourceforge.net/doc/tcmalloc.html it makes the disk based index unreadable (it fails with  a readNode: failed reading the correct node type information).

Writing it without the library and then reading it with the library linked in works fine.

**Comment by hobu** [comment]
ok?

Without a recipe to reproduce or investigation on what might be causing this, it is not going to be picked up.

**Comment by spansh** [comment]
I'll see what I can run up
