### ISSUE TITLE
Unable to bulkload data file

### ISSUE THREAD

**Issue by ankit-1517** [libspatialindex/libspatialindex#195]
I'm trying to get started with the library using the example given [here](https://github.com/libspatialindex/libspatialindex/blob/master/test/rtree/RTreeBulkLoad.cc).

I create a file (data/2d.txt) with 10 million, 2D points in [0, 1]. There's nothing else in the file.

When I run it, I get: 

```
./RTreeBulkLoad data/2d.txt temp.txt 100 0.7
******ERROR******
IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.
```

But the file is not empty! It has 10 million points. Am I missing something here? Thanks...

**Comment by hobu** [comment]
That specific file runs in the test suite. Follow it exactly to replicate.
