### ISSUE TITLE
CMake imported targets: define a namespace

### ISSUE THREAD

**Issue by SpaceIm** [libspatialindex/libspatialindex#205]
master branch seems to export CMake targets now (thanks, v1.9.3 did not export targets AFAIK), but targets are not namespaced.

Could you add a namespace please (best practice for imported targets: https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html)?

>When providing imported targets, these should be namespaced (hence the Foo:: prefix); CMake will recognize that values passed to target_link_libraries() that contain :: in their name are supposed to be imported targets (rather than just library names), and will produce appropriate diagnostic messages if that target does not exist (see policy CMP0028).

**Comment by hobu** [comment]
@SpaceIm please grab #205 and confirm if this is what is going to work for you.

**Comment by SpaceIm** [comment]
@hobu yes that's it, thanks a lot :)
