### ISSUE TITLE
no configure file in latest release

### ISSUE THREAD

**Issue by wuhland** [libspatialindex/libspatialindex#206]
Looks like configure got added to .gitignore and is not included in the latest release https://github.com/libspatialindex/libspatialindex/releases/download/1.9.2/spatialindex-src-1.9.2.tar.gz

**Comment by mortymacs** [comment]
Yes, the configure file is no longer needed for compilation. All changes have been applied to the CMakefile.

**Comment by hobu** [comment]
libspatialindex is CMake-only going forward from the 1.9.2 release.
