### ISSUE TITLE
Doxygen docs are missing

### ISSUE THREAD

**Issue by rcoup** [libspatialindex/libspatialindex#215]
https://libspatialindex.org/en/latest/ links to https://libspatialindex.org/en/latest/doxygen/ for the class documentation, which is returning a 404.

**Comment by rcoup** [comment]
The files seem to be present at https://github.com/libspatialindex/libspatialindex.github.com/tree/master/doxygen so maybe something with the ReadTheDocs configuration?

**Comment by hobu** [comment]
RTD doesn't do doxygen as far as I know. I'm not sure what to do

**Comment by rcoup** [comment]
Ah, I figured it had worked at some point in the past...

Caveat: I know next-to-nothing about sphinx or doxygen, and not much more about RTD.

* https://stackoverflow.com/a/41199722/2662 suggests you can tell Sphinx/RTD to call doxygen during the build then add the directory as an extra html path
* https://breathe.readthedocs.io/en/latest/readthedocs.html has basically the same thing but also shows the env var to check if the sphinx build is running on RTD so it wouldn't affect local builds.

Or if you want to cross-reference between sphinx & doxygen, looks like [Breathe](https://breathe.readthedocs.io) is [the way to go](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/#setting-up-read-the-docs), but that's clearly a bigger task.

**Comment by hobu** [comment]
Feel free to make a PR that implements RTD Sphinx support. I would be happy to have it, but I didn't see how to do it with some cursory searching. My goal with the RTD transition was to remove any external service dependencies in hope of being able to hand the keys to libspatialindex to any maintainer who wished to take it over and not cause any disruption.
