### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by xiaoheling** [libspatialindex/libspatialindex#218]
how to run your project？
when  I  input the command  “./run”
it shows  ./run: line 4: test-rtree-Generator: can not find command

**Comment by mortymacs** [comment]
You can complie these files manually:

```
$ cd libspatialindex/test/geometry
$ g++ -o test-geometry-Intersection Intersection.cc -l spatialindex
$ ./test-geometry-Intersection
```

@hobu Should we add these directories in the CMake file as well?

**Comment by xiaoheling** [comment]
> You can complie these files manually:
> 
> ```
> $ cd libspatialindex/test/geometry
> $ g++ -o test-geometry-Intersection Intersection.cc -l spatialindex
> $ ./test-geometry-Intersection
> ```
> 
> @hobu Should we add these directories in the CMake file as well?

thanks for your answer.

**Comment by mortymacs** [comment]
> Hello
> 
> I followed your instructions but i get the following error: `./test-geometry-Intersection: error while loading shared libraries: libspatialindex.so.6: cannot open shared object file: No such file or directory`
> 
> What am i doing wrong?

Hi,

You need to update the `LD_LIBRARY_PATH` environment variable to point to the `bin` directory path:

```
> LD_LIBRARY_PATH=../../bin ./test-geometry-Intersection
```

All steps:
```bash
> cmake . && make -j8
> cd libspatialindex/test/geometry
> g++ -o test-geometry-Intersection Intersection.cc -l spatialindex -I../../include/ -L../../bin
~/libspatialindex/test/geometry on master ?5                                                                 at 18:11:27
> ./test-geometry-Intersection
./test-geometry-Intersection: error while loading shared libraries: libspatialindex.so.6: cannot open shared object file: No such file or directory
~/libspatialindex/test/geometry on master ?5                                                                 at 18:11:31
> LD_LIBRARY_PATH=../../bin ./test-geometry-Intersection
~/libspatialindex/test/geometry on master ?5
> echo $?
0
```

**Comment by psimatis** [comment]
thank you!
