### ISSUE TITLE
Migration problems v1.9.0 --> v1.9.3

### ISSUE THREAD

**Issue by pmeems** [libspatialindex/libspatialindex#224]
We've been using libSpatialIndex with [MapWinGIS](https://github.com/MapWindow/MapWinGIS) (Open Source as well) for years now.
We're currently in the process of migrating MapWinGIS from building with VS2017 (toolset v140) to VS2019 (toolset v142) and upgrading GDAL2 and PROJ.4 to GDAL3+ and PROJ.7.

We also want to upgrade our current version of libSpatialIndex from v1.9.0 to the latest version (v1.9.3).
But when we do we get strange link errors, like
```
LNK2005	"public: char const * __thiscall std::_Locinfo::_Getdays(void)const " (?_Getdays@_Locinfo@std@@QBEPBDXZ) already defined in SpatialIndex-mw.lib(Statistics2.obj)
```

We're not sure what this means. Are there breaking changes in the latest version we need to address?

We compile libSpatialIndex ourselves using `stdcpp14` and `stdc11` and we make a few changes to the code:

- Build as a static lib
- Remove the SIDX_DLL keyword from include files
- Change the project name to "spatialindex-mw"
- Change the index file extensions from "dat" and "idx" to "mwd" and "mwx"

The last step is for historical reasons because before we used libSpatialIndex we used a custom spatial indexer.
The calling code is at https://github.com/MapWindow/MapWinGIS/tree/develop/src/Utilities/SpatialIndex

When we stick with v1.9.0 we don't have any problems.

Please advice.

**Comment by hobu** [comment]
None of the libspatialindex code uses Getdays. I'm not sure what's going on, and if you're changing all of the code to satisfy your usage, how this particular issue is libspatialindex's.

**Comment by pmeems** [comment]
Thanks Howard for your reply.
This workflow was made years ago by a developer who's no longer around.
Perhaps you have a better suggestion on how to create a static library from libSpatialIndex using VS2019?

**Comment by hobu** [comment]
#223 was a start on fixing that, but it doesn't look like it was completed

**Comment by pmeems** [comment]
I made the changes suggested in #223 and don't have the 160+ error anymore.
Only one remains:
`Unresolved external symbol "public: virtual __thiscall IdVisitor::~IdVisitor(void)" (??1IdVisitor@@UAE@XZ) referenced in function "public: virtual void __thiscall SpatialIndex::RTree::RTree::internalNodesQuery(class SpatialIndex::IShape const &,class SpatialIndex::IVisitor &)"`

But I'm not a C++ developer, so I'm stuck now.

Does anybody here have a suggestion?

**Comment by tangxiaodao** [comment]
Is this problem solved?

**Comment by pmeems** [comment]
> Is this problem solved?

This is not solved yet. It is not yet possible to use LibSpatial as a static lib.
Feel free to give it a try.

**Comment by pmeems** [comment]
Just to inform you.
We're now using vcpkg and its LibSpatial package.
With just a few minor configuration settings we've got this working.
So this issue can be closed now.
