### ISSUE TITLE
index-tests.sh is flaky

### ISSUE THREAD

**Issue by sebastic** [libspatialindex/libspatialindex#247]
index-tests.sh in 2.0.0b1 no longer silently fails (#244), but now it's flaky.

It failed as part of the Debian package build initially:

 https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5782956

But succeeded after a retry:

 https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5783051

We're seeing the same failures on some of the build daemons.

Build logs: [amd64](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=amd64&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716917823&raw=0), [armel](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=armel&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716919287&raw=0), [armhf](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=armhf&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716918020&raw=0), [mips64el](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=mips64el&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716918278&raw=0), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=hurd-i386&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716919126&raw=0), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=powerpc&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716918363&raw=0), [sparc64](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=sparc64&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716919613&raw=0), [x32](https://buildd.debian.org/status/fetch.php?pkg=spatialindex&arch=x32&ver=2.0.0%7Eb1-1%7Eexp1&stamp=1716918102&raw=0)

Overview: https://buildd.debian.org/status/logs.php?pkg=spatialindex&ver=2.0.0%7Eb1-1%7Eexp1&suite=experimental

Current status: https://buildd.debian.org/status/package.php?p=spatialindex&suite=experimental

[2.0.0b2](https://buildd.debian.org/status/logs.php?pkg=spatialindex&ver=2.0.0%7Eb2-1%7Eexp1&suite=experimental) builds are better so far, but it doesn't contain any relevant changes, it's just luck that these builds succeeded.

[2.0.0b3](https://buildd.debian.org/status/logs.php?pkg=spatialindex&ver=2.0.0%7Eb3-1%7Eexp1&suite=experimental) initially failed on [hppa](https://buildd.debian.org/status/logs.php?pkg=spatialindex&arch=hppa) & [sparc64](https://buildd.debian.org/status/logs.php?pkg=spatialindex&arch=sparc64) but succeeded when retried.

**Comment by hobu** [comment]
that's frustrating. Thanks for the report. It seems like it is always the tprtree test that is failing. 

I'm confused about the assertion report of https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5782956 because the line and code it refers to doesn't exist in `main` https://github.com/libspatialindex/libspatialindex/blob/main/src/tprtree/Node.cc#L382. It also doesn't exist on that line in the tarball at https://github.com/libspatialindex/libspatialindex/releases/tag/2.0.0b3. This was one of the lines that I had removed between b2 and b3...

**Comment by sebastic** [comment]
> I'm confused about the assertion report of https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5782956 because the line and code it refers to doesn't exist in `main` https://github.com/libspatialindex/libspatialindex/blob/main/src/tprtree/Node.cc#L382. It also doesn't exist on that line in the tarball at https://github.com/libspatialindex/libspatialindex/releases/tag/2.0.0b3. This was one of the lines that I had removed between b2 and b3...

That Salsa CI job is for 2.0.0b1.

 https://github.com/libspatialindex/libspatialindex/blob/2.0.0b1/src/tprtree/Node.cc#L382

The two recent failures of 2.0.0b3 are:
```
test-tprtree-TPRTreeLoad: ./src/spatialindex/MovingRegion.cc:415: virtual bool SpatialIndex::MovingRegion::intersectsRegionInTime(const Tools::IInterval&, const SpatialIndex::MovingRegion&, Tools::IInterval&) const: Assertion `tmin <= tmax' failed.
./run: line 9: 17281 Aborted                 (core dumped) test-tprtree-TPRTreeLoad mix tree 10 > res
```
https://github.com/libspatialindex/libspatialindex/blob/2.0.0b3/src/spatialindex/MovingRegion.cc#L415
```
test-tprtree-TPRTreeLoad: ./src/spatialindex/MovingRegion.cc:969: virtual double SpatialIndex::MovingRegion::getIntersectingAreaInTime(const Tools::IInterval&, const SpatialIndex::MovingRegion&) const: Assertion `c.m_t >= tmin && c.m_t <= tmax' failed.
./run: line 12: 3490376 Aborted                 (core dumped) test-tprtree-TPRTreeLoad data tree 20
```
https://github.com/libspatialindex/libspatialindex/blob/2.0.0b3/src/spatialindex/MovingRegion.cc#L969

**Comment by hobu** [comment]
> We might want to build with NDEBUG to compile out the asserts.

If you compile with Release or RelWithDebugInfo as the `CMAKE_BUILD_TYPE`, `NDEBUG` will be added as a default flag by CMake.

**Comment by sebastic** [comment]
Using NDEBUG hides the assert issues, so I don't consider it a good solution.

Since the b3 failures only occurred on non-release architectures, there might not be a problem on amd64 and arm64. But since the tests are flaky I don't have a lot of confidence in that.

I'd issue at least one RC before releasing 2.0.0.

**Comment by hobu** [comment]
> I'd issue at least one RC before releasing 2.0.0.

Ok, I will do that and shut off the tprtest that was the cause of the issues. That index type needs more attention and proper testing.

**Comment by hobu** [comment]
Posted https://github.com/libspatialindex/libspatialindex/releases/tag/2.0.0b4

**Comment by sebastic** [comment]
b4 is looking good so far: https://buildd.debian.org/status/package.php?p=spatialindex&suite=experimental

**Comment by hobu** [comment]
Good to go now @sebastic ?

**Comment by sebastic** [comment]
Good enough for rc1.

**Comment by hobu** [comment]
> Good enough for rc1.

I don't think that's necessary at this point. We've already had an alpha and 4 betas. No one else is testing anything or even paying attention except for you. All your builders are ✅, so I'm inclined to push out the final.

**Comment by sebastic** [comment]
FWIW, b4 should have been rc1.

I expect release candidates to get more attention from packagers, but nothing beats getting the new version in the next Debian and Ubuntu releases.

Did you ask the QGIS developers to test the pre-releases? QGIS the most significant reverse dependency, and I think Jurgen is also the maintainer of the libspatialindex OSGeo4W package.

**Comment by hobu** [comment]
> Did you ask the QGIS developers to test the pre-releases?

I reached out but no one responded. Switching to asking forgiveness instead of asking for permission at this point.

**Comment by hobu** [comment]
https://github.com/libspatialindex/libspatialindex/releases/tag/2.0.0 release posted. If there are any issues, it is now very easy to make a new release by pushing a tag. To anyone paying attention, I would be quite happy to handover maintenance activities to someone who can be more active.

**Comment by sebastic** [comment]
The test is still flaky in 2.0.0:
```
test-tprtree-TPRTreeLoad: ./src/spatialindex/MovingRegion.cc:969: virtual double SpatialIndex::MovingRegion::getIntersectingAreaInTime(const Tools::IInterval&, const SpatialIndex::MovingRegion&) const: Assertion `c.m_t >= tmin && c.m_t <= tmax' failed.
./run: line 12:  2708 Aborted                 (core dumped) test-tprtree-TPRTreeLoad data tree 20
```
https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5823674

```
test-tprtree-TPRTreeLoad: ./src/spatialindex/MovingRegion.cc:938: virtual double SpatialIndex::MovingRegion::getIntersectingAreaInTime(const Tools::IInterval&, const SpatialIndex::MovingRegion&) const: Assertion `c.m_t >= tmin && c.m_t <= tmax' failed.
./run: line 12:  3974 Aborted                 (core dumped) test-tprtree-TPRTreeLoad data tree 20
```
https://salsa.debian.org/debian-gis-team/spatialindex/-/jobs/5823676
