### ISSUE TITLE
How to build with the Android 

### ISSUE THREAD

**Issue by yujream** [libspatialindex/libspatialindex#256]
I want to compile into a version that can be used by Android. I haven't seen the relevant compilation document. How can I support it? Thank you!

**Comment by hobu** [comment]
libspatialindex predates the existence of Android by nearly a decade. We would happily merge an addition to the documentation that provides directions on how to compile it for Android.

**Comment by yujream** [comment]
> libspatialindex predates the existence of Android by nearly a decade. We would happily merge an addition to the documentation that provides directions on how to compile it for Android.

When is it updated, I checked the latest document and did not find the relevant content. Looking forward to your reply, thank you!

**Comment by hobu** [comment]
There is no such document. I was inviting you to read the source and CMake configuration to discover how to build it on Android and provide one.

**Comment by yujream** [comment]
> There is no such document. I was inviting you to read the source and CMake configuration to discover how to build it on Android and provide one.

I will try it, thank you for answering!
