### ISSUE TITLE
Use of virtual inheritance for Point and Region

### ISSUE THREAD

**Issue by FreddieWitherden** [libspatialindex/libspatialindex#257]
Does anyone know why virtual inheritance of `IShape` is needed for the `Point` and `Region` classes?  This greatly increases the costs of dynamic casts and slows down the code substantially (for an application which just uses an RTree the slowdown is ~20%).

Going through the inheritance hierarchy I can't see any diamonds.  We have `TimePoint` and `TimeRegion` which inherit from `Point` and `Region`, respectively, along with `ITimeShape` but this inherits from `IInterval` which is a base class (and so no second `IShape` in the hierarchy).

Thus, if my current understanding is correct we can remove the `virtual` bit and get an immediate performance boost.

**Comment by hobu** [comment]
> Does anyone know why virtual inheritance of IShape is needed for the Point and Region classes?

It was the style of the day. See https://en.wikipedia.org/wiki/Design_Patterns for more detail.

Removal of all of most of it is unlikely to impact users and indeed provide a significant performance bump. PR away!

**Comment by FreddieWitherden** [comment]
Resolved (at least for Region and Point's).
