### ISSUE TITLE
Missing vendored gtest

### ISSUE THREAD

**Issue by davisp** [libspatialindex/libspatialindex#52]
Apparently the recommendation is to vendor a copy of gtest which appears to have not been done.

https://code.google.com/p/googletest/wiki/FAQ#Why_is_it_not_recommended_to_install_a_pre-compiled_copy_of_Goog

**Comment by hobu** [comment]
gtest building needs to be added to cmake configuration too.

**Comment by hobu** [comment]
done in @f0b22a2fa99d2bf0b16052eb919671880cd507b2
