### ISSUE TITLE
Packaging issue with vs2013 build

### ISSUE THREAD

**Issue by naihil** [libspatialindex/libspatialindex#65]
libspatialindex-1.8.5-win-msvc-2013-x64.zip contains bin, include, lib directories and libspatialindex-1.8.5-1-src.tar.bz2 archive, which contains bin, lib, include directories too, not source.

**Comment by hobu** [comment]
the windows build is just install file output from the `make install` target of cmake. You'll need both the binary and the source tree if you need source files.

**Comment by naihil** [comment]
I think you dont understand me. I downloaded libspatialindex-1.8.5-win-msvc-2013-x64.zip from http://download.osgeo.org/libspatialindex. Archive has following structure:
libspatialindex-1.8.5-win-msvc-2013-x64.zip:
|--build
|----bin
|------spatialindex_c-64.dll
|------spatialindex-64.dll
|----include
|------.....
|----lib
|------.....
|----libspatialindex-1.8.5-1-src.tar.bz2
|------bin
|--------spatialindex_c-64.dll
|--------spatialindex-64.dll
|------include
|--------.....
|------lib
|--------.....

I think that libspatialindex-1.8.5-1-src.tar.bz2 should contain source or should be removed as duplicate.

**Comment by hobu** [comment]
ah, yes. This will be removed when we have another libspatialindex release. It must have been in the tree when I tar'd it up.
