### ISSUE TITLE
Bulk Load R* Tree with Point data

### ISSUE THREAD

**Issue by myth17** [libspatialindex/libspatialindex#69]
I am studying the test cases to understand if bulk loading a R* tree with Point data is possible.

The function RTree::createAndBulkLoadNewRTree takes a stream as one of the parameter which has a getNext function that return an IData. The RTree::Data constructor only supports creating an object with Region as one of the argument and not a Point.

Is bulk loading with Point data available?

**Comment by hobu** [comment]
Point is assumed if the xmin=xmax and ymin=ymax when compared using an epsilon of the data type (float).

**Comment by ankit-1517** [comment]
> Point is assumed

Does this mean that only xmin and ymin are stored (and thus saving some memory)?
