### ISSUE TITLE
Multi-Thread NN Search Corrupted Data File

### ISSUE THREAD

**Issue by Nathaniel1990** [libspatialindex/libspatialindex#77]
I want to perform incremental NN Search on RTree towards different queries. To improve the efficiency, I decide to perform the search simultaneously with the help of threads. Therefore I rewrite the `nearestNeighborQuery` procedure and add a `lock` in the `while` loop. In the beginning, the program is executed quite well. But unexpectedly, after executing the program several times, the data file is corrupted because the exception ‘*SpatialIndex::DiskStorageManager: Corrupted data file*’ is threw out.

I don't know why just reading the tree data and performing some search will corrupt the data file.  Any idea to explain this and solve the program? Thanks!

**Comment by hobu** [comment]
libspatialindex is not completely threadsafe at this time.
