### ISSUE TITLE
Impossible to use libspatialindex using MSVS2013 in combination with boost

### ISSUE THREAD

**Issue by SieLink** [libspatialindex/libspatialindex#78]
I am using libspatialindex in one of my projects. I am currently switching to MSVS2013. 
As of now, I used MSVS2008 on the Windows side. 
As it appears, it is impossible to use libspatialindex in combination with Boost (which is used in the same project) starting with MSVS2010.

Reason: Starting with MSVS2010, Microsoft defines its own stdint.h 
header file. Boost starts pulling this header file as soon as it is available.

See: include\boost\config\compiler\visualc.hpp:
#if _MSC_VER >= 1600
#define BOOST_HAS_STDINT_H
#endif

Libspatialindex has its own defines in Tools.h. These are created 
independently of the Visual Studio version. There is just a simple 
check for the MS OS.

As the defines created by Libspatialindex even differ from the MS 
version of stdint.h, compile errors are inevitable:

\libspatialindex\include\spatialindex\tools/Tools.h(31): error C2371: 'int8_t' : redefinition; different basic types
\VC\include\stdint.h(8) : see declaration of 'int8_t'

Could you please adapt the check in Tools.h before setting own stdint defines.
Instead of just checking for Windows OS, there should be the same _MSC_VER check just like Boost does it.

**Comment by hobu** [comment]
Please provide a pull request implementing this and I will be happy to merge it.

**Comment by SieLink** [comment]
I just saw myself that the proposed changed exists in a very similar way.
The commit ID is 924124480889e2d3bcf98c47a5800f7e4a779774 (created by mloskot on Jun 4, 2013).

Merging this change will properly fix the issue.

**Comment by hobu** [comment]
Please let me know if this fixes the issue for you.

**Comment by SieLink** [comment]
The changes solves the compile problem.
But it also exposes hundreds of the following warnings. Eg:
> src\include\spatialindex\tools/Tools.h(139): warning C4251: 'Tools::IndexOutOfBoundsException::m_error' : class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'Tools::IndexOutOfBoundsException' (..\src\mvrtree\Index.cc)

To  get rid of these again, I simply moved the two lines for disabling this warning under the #if (defined) statement following directly below:

```
#if (defined _WIN32 || defined _WIN64 || defined WIN32 || defined WIN64) && !defined __GNUC__
  #ifdef SPATIALINDEX_CREATE_DLL
    #define SIDX_DLL __declspec(dllexport)
  #else
    #define SIDX_DLL __declspec(dllimport)
  #endif

// Nuke this annoying warning.  See http://www.unknownroad.com/rtfm/VisualStudio/warningC4251.html
//#pragma warning( disable: 4251 )

#else
  #define SIDX_DLL
#endif
```

Sorry for not adding this directly to the sources. I hope this form is acceptable.

**Comment by hobu** [comment]
Please test that one and see if I got it to shut up.

**Comment by SieLink** [comment]
Yes, this removes the warning. 

But you should also remove the duplicated disabling of the warning in line 41/42. Line 55/56 do the trick completely.

**Comment by SieLink** [comment]
Exactly what I had in mind. Works fine for me.
