### ISSUE TITLE
Multiple warnings after "Fix C API" PR

### ISSUE THREAD

**Issue by naihil** [libspatialindex/libspatialindex#85]
@miklos1, I have multiple warnings after PR #82:

`git\include\spatialindex\capi\Index.h(34): warning C4099: 'Index' : type name first seen using 'struct' now seen using 'class'`
`git\include\spatialindex\capi\sidx_config.h(104) : see declaration of 'Index'`

In include\spatialindex\capi\Index.h (34):
`class SIDX_DLL Index`
and in include\spatialindex\capi\sidx_config.h (104):
`typedef struct Index *IndexH;`

**Comment by miklos1** [comment]
That's all right. If the warning really bothers you, you can rename the "`struct`" to something that doesn't clash with any other name, for example:
```typedef struct my_very_unique_struct_name_for_Index *IndexH;```

**Comment by hobu** [comment]
Fixed in https://github.com/libspatialindex/libspatialindex/commit/f0b22a2fa99d2bf0b16052eb919671880cd507b2#diff-165dcc64c6de7298be3e5113ed711d95R104
