### ISSUE TITLE
Bulk loading an in-memory R-tree (example)?

### ISSUE THREAD

**Issue by gevago01** [libspatialindex/libspatialindex#87]
Hello all, 

 I don't know if this is the right place to post this; but I am looking for a good example of how to bulk load points into a main-memory R-tree? Unfortunately the wiki only describes single point addition. Is there something I've missed in the documentation or the wiki? I appreciate your help.

Many thanks,
Giannis.

**Comment by r-barnes** [comment]
I am also looking for such an example.

**Comment by r-barnes** [comment]
There's a test called `RTreeBulkLoad.cc` which might be useful.
