### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by citibeth** [libspatialindex/libspatialindex#95]
The docs are lacking.  For example, I had to dig into the source code to find out what the `len` parameter for `insertData()` does.

Once I found out... I would say that the RTree should not be trying to do this `memcpy()`.  Most importantly, `memcpy()` doesn't work in general for C++.  And there are other ways to get the memory stored if needed.  I wouldn't try to solve this problem in `libspatialindex`.

**Comment by hobu** [comment]
We will happily take a patch to improve this area of the library.
