### ISSUE TITLE
Do Not Pollute the Top-Level Namespace!

### ISSUE THREAD

**Issue by citibeth** [libspatialindex/libspatialindex#96]
The library defines (among other things) a class named `::Index`.  Not only is this in the top-level namespace (producing potential namespace conflicts), it is also a rather generic name.

Just don't do it.  All symbols visible to users should be defined in a namespace called `spatialindex`.  (By convention, namespace names are lowercase).

**Comment by hobu** [comment]
It's been this way for more than 15 years, and simply changing it now for purity's sake will break people for no good reason.

**Comment by citibeth** [comment]
Calling it "purity" sake is presumptuous.  If there's another library out there that also creates a symbol cold `::Index`, then users linking to that library as well as `libspatialindex` *will* have problems.  Given that one library has already done so, it's not inconceivable that another one would as well.

Just because a poor choice was made 15 years ago, doesn't mean you have to perpetuate it forever.  There are a few ways this can be addressed:

1. Make a whole bunch of backwarrds-incompatible changes at once, and then push them all together.  Python took this approach with the transition to Python3.  Many other projects have done this as well.  Maybe this would go with the C++11 project.

2. Move the symbols out of the top-level namespace, and then create a compatibility include file that would look something like this:
```
typedef SpatialIndex::Index Index;
```

3. Same as (2), but have the compatibility aliases included automatically, so existing users don't have to change a thing.  Make a new set of include files for users of the "new" API.
