### ISSUE TITLE
Don't use quotes in includes!!!

### ISSUE THREAD

**Issue by citibeth** [libspatialindex/libspatialindex#97]
Inside `.h` files, `libspatialindex` should do:
```
#include <spatialindex/xyz.h>
```
instead of
```
#include "xyz.h"
```

That is because the `.h` file might be included by a user.  And in that case, having `#include "xyz.h"` will require NOT JUST `-Ispatialindex/include` on the command line, but also `-Ispatialindex/include/spatialindex`.  And it pollutes the top-level `#include` namespace.  It just feels sloppy, and can cause unnecessary problems.

**Comment by hobu** [comment]
I agree the include tree should be improved. I think the intention was to do that as part of the wider C++11 refactoring effort, but that has thus far not taken off.

**Comment by citibeth** [comment]
This change is as simple as a set of search-and-replace, and would have essentially zero effect on users.  There is no need to bundle it with a set of much larger changes.
